language: cpp
os: windows
install:
        - choco install windows-sdk-10-version-1903-all
        - PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'
script:
        - ./run.bat
        - PowerShell -File ./Team06/Tools06/runAllSysTest.ps1