language: cpp
os: windows
env:
        - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\15.0\Bin"
script:
        - export PATH=$MSBUILD_PATH:$PATH
        - MSBuild.exe Team06/Code06/StartupSPASolution.sln /p:Configuration=Release'
        - dir
        - dir "C:\Program Files (x86)"
